### ISSUE TITLE
[Mod will not let you log in on servers] 

### ISSUE THREAD

**Issue by FullMetalMaster** [dudek26/Create-Blazing-Hot#3]
**Describe the bug**
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot write a null registry entry!

**To Reproduce**
Steps to reproduce the behavior: just put the mod in a server and log in with a client

**Minecraft version**
[latest.log](https://github.com/user-attachments/files/16831650/latest.log)

1.20.1
**Mod version**
forge Create: Blazing Hot v0.6.1 for Forge 1.20.1

**Environment**
Multiplayer
![image](https://github.com/user-attachments/assets/12dfe153-b433-4e4d-991d-6c3bc2d5ac34)

**Comment by dudek26** [comment]
Hi, thanks for your report. I've made a [temporary fix](https://github.com/user-attachments/files/16838582/create_blazing_hot-0.6.2%2Bforge-mc1.20.1-build.147.jar.zip)  that should let you join the server, but some Blaze Mixing recipe won't display their fuel requirement. I will release a new version containing a proper fix this week

**Comment by dudek26** [comment]
fixed in [0.6.2](https://modrinth.com/mod/create-blazing-hot/version/0.6.2+forge-mc1.20.1)
