### ISSUE TITLE
[Bug] Connection reset

### ISSUE THREAD

**Issue by Astrolava** [dudek26/Create-Blazing-Hot#6]
When I install this mod into my forge 1.20.1 server, and my forge 1.20.1 client, I am no longer able to log in.  It stops at "Encrypting" after clicking "join world" and eventually returns an "internal error: connection reset".
The error happens whether I connect from the same machine (127.0.0.1), over LAN (192.168...), and even over WAN.
The server console says "took too long".  I've tried increasing the timeout using the following java parameters:
Server:

-Dfml.readTimeout=6000 
-Dfml.connectionTimeout=6000
-Dsun.net.client.defaultConnectTimeout=900000 
-Dsun.net.client.defaultReadTimeout=900000

Client:
-Dfml.readTimeout=6000 
-Dfml.connectionTimeout=6000

These didn't fix the issue, or make any noticeable difference.  I have the following mods installed:

architectury-9.2.14-forge
lmft-1.0.4+1.20.1-forge
create_blazing_hot-0.6.2+forge-mc1.20.1
resourcefulconfig-forge-1.20.1-2.1.2
ad_astra-forge-1.20.1-1.15.18
Mekanism-1.20.1-10.4.9.61
indestructible-1.19-0.5
productivetrees-1.20.1-0.2.6
findme-3.2.1-forge
DimensionLocalizedInventories-1.20.1-1.9FE
saveandloadinventories-1.20.1-3.4
gravestone-forge-1.20.1-1.0.23
hardernaturalhealing-1.20-46.1.14
resourcefullib-forge-1.20.1-2.1.29
prometheus-forge-1.20.1-1.2.5
rainbowlamp-forge-1.3-1.20
customizableelytra-forge-2.1.2+1.20
cobweb-forge-1.20.1-1.0.0
BetterFlight-1.20.1-forge-2.2.0
paddedelytras-1.20-1.0
pyrotechnic-elytra-forge-1.20.1-1.0.0
iChunUtil-1.20.1-Forge-1.0.0
evenmoredragons-1.20.1-1.0.4
moredragons-1.3.1
dragonmounts-1.20.1-1.2.3-beta
bjornlib-forge-1.0.19.5-1.20.1
heartbalance-1.20.1-1.0.3
createcherry-0.4-1.20.1
Bacterium-Forge_1.20.1-1.0
ctd-core-1.20.1-2.4.9
mo-glowstone-lamps-1.20.1-1.4.2
mo-glowstone-1.20.1-2.4.6
mo-glowstone-plus-1.20.1-1.1.2
rainbowoaks-forge-1.20-1.0.0
clay-1.0.0-forge-1.20.1-1.20.4
FlowerBreeding-Fabric-Neo-Forge-Quilt-1.20.x
collective-1.20.1-7.84
sleepsooner-1.20.1-4.6
Quad-1.2.5+1.20.4-Forge
[1.20.1]MoreCraftingTables-5.1.3
paintable-1.5a-1.20.1
wallpapers-1.2a-Forge-1.20.1
dye_depot-1.0.0-forge
lenientcreepers-1.20-1.0.2
kotlinforforge-4.11.0-all
sophisticatedcore-1.20.1-0.6.26.668
curios-forge-5.10.0+1.20.1
Jade-1.20.1-forge-11.11.1
JustEnoughResources-1.20.1-1.4.0.247
open-parties-and-claims-forge-1.20.1-0.23.2
XaerosWorldMap_1.39.0_Forge_1.20
NaturesCompass-1.20.1-1.11.2-forge
sophisticatedbackpacks-1.20.1-3.20.7.1075
toms_storage-1.20-1.6.8
sophisticatedstorage-1.20.1-0.10.26.817
create_ironworks-2.5.0-forge-1.20.1
createenchantablemachinery-1.20.1-1.5.4
create_optical-0.1.1
create_deep_dark-1.5.0-forge-1.20.1
create_aquatic_ambitions-1.20.1-1.1.1
vintageimprovements-1.20.1-0.2.0.3
citadel-2.6.0-1.20.1
domesticationinnovation-1.7.1-1.20.1
carryon-forge-1.20.1-2.1.2.7
polymorph-forge-0.49.5+1.20.1
SkinnedCarts-1.20.1-2.0.1
hamsters-forge-1.0.3-1.20.1
blueprint-1.20.1-7.1.0
autumnity-1.20.1-5.0.1
Create-Guardian-Beam-Defense-1.3.0b-1.20.1
createaddition-1.20.1-1.2.4e
betterdays-1.20.1-3.1.0.6-FORGE
geckolib-forge-1.20.1-4.4.9
loafcats-1.1-1.20.1
petrolsparts-1.20.1-1.0.3
petrolpark-1.20.1-1.0.1-all
Xaeros_Minimap_24.4.0_Forge_1.20
jei-1.20.1-forge-15.19.0.88
Create-DnDesire-1.20.1-0.1b.Release-Early-Dev
flib-1.20.1-0.0.14
supermartijn642configlib-1.1.8-forge-mc1.20
supermartijn642corelib-1.1.17a-forge-mc1.20.1
chunkloaders-1.2.8a-forge-mc1.20.1
botarium-forge-1.20.1-2.3.4
create-new-age-forge-1.20.1-1.1.2
create-1.20.1-0.5.1.h

I know the list of mods is a little large, so it's very possible that a mod incompatibility exists here.

**Comment by dudek26** [comment]
Hi, could you provide server and client logs?

**Comment by Astrolava** [comment]
Sure, is there anything in the logs that I should omit?  Any personal info or anything?

**Comment by dudek26** [comment]
Server logs your IP address on join so make sure to delete any occurrences of your ip, I'm not sure if there is anything else

**Comment by Astrolava** [comment]
Server:
[debug.log](https://github.com/user-attachments/files/17229177/debug.log)
[latest.log](https://github.com/user-attachments/files/17229184/latest.log)

Client:
[debug.log](https://github.com/user-attachments/files/17229191/debug.log)
[latest.log](https://github.com/user-attachments/files/17229192/latest.log)

**Comment by dudek26** [comment]
I don't see anything suspicious in the logs and I'm unable to replicate this, does removing Create: Blazing Hot solve the issue? If yes, that would probably be mod incompatibility.

**Comment by Astrolava** [comment]
Yes, if I remove the mod I am able to join the world.  
If I'm able to isolate which mod is causing the incompatibility, would that assist you in resolving the potential issue?

**Comment by dudek26** [comment]
Yes, that would be very helpful

**Comment by Astrolava** [comment]
After disabling all other mods aside from create and create:blazing hot, I noticed that I still struggle to log in.
With nearly 100 mods, and no create:blazing hot - I log in successfully each time.
I installed a fresh forge server, added create and create:blazing hot, but could only log in successfully into the server 1/10 times.
I'm not sure what to do from here.

Update:  Disabling offline mode / enforce secure profiles has no effect.
The server and client are on the same machine currently, though switching to a LAN/WAN machine has no effect.
There is something within the blazing hot mod itself which is causing the struggle while logging in.

I should also note that while the client/server struggle to connect at a rate of 1/10 with only the create/blazing hot mods installed, with any other mod included - even the smallest mod, the rate of failure seems to be much higher.
I have yet to connect even once while using >2 mods while "blazing hot" is active.

**Comment by dudek26** [comment]
Okay, I think I have managed to replicate this issue **once** by updating Forge on my server to the latest 1.20.1 version (I used 47.3.7 before) because my server froze after I tried to join it, but I'm unable to replicate it after a restart. 

My suspicion is that I may have written some really unoptimized code that makes Forge servers struggle, but I have no idea where this code could be.

I will leave this issue open for now and I will come back to this later.

**Comment by Astrolava** [comment]
Thank you, I appreciate it and look forward to using this mod in the future.
By the way, if you create a discord server, I may be able to help - I haven't used Java in a few years, but I'm a programmer.
Let me know.

**Comment by dudek26** [comment]
Okay, I've investigated the issue a bit further and here is what I've found:
- When loading a singleplayer world with the 0.6.1 version of the mod "Reading world data" takes ~2 seconds
- When loading the same singleplayer world with the 0.6.2 version "Reading world data" can take **up to 15 seconds**
- I've also noticed some issues when the server was loading the world, so I believe this may be connected to your issue

0.6.2 added new Modern Lamp variants and some of them may have too much different blockstates. Take Small Modern Lamp Panel as an example:
- It has 6 different properties: facing, lit, locked, powered, waterlogged and offset.
- There are 6 possibles values for 'facing' and 9 possible values for 'offset', the rest is true/false. If I understand Blockstates correctly, it means that the game registers **864 possible combinations** of each Small Modern Lamp Panel variant.
- There are 16 color variants of every Modern Lamp, so there are **13 824 combinations of Small Modern Lamp Panels**.

Here are the blockstate.json resource files for all Black Modern Lamps and their sizes.
![image](https://github.com/user-attachments/assets/bad9e604-b53a-4922-b1ce-30b7a02d5194)

I will try to optimise the lamps and release a new version this weekend. If you want to play with the mod on your server, you should be able to use [the patched 0.6.1 forge version](https://github.com/user-attachments/files/16838582/create_blazing_hot-0.6.2%2Bforge-mc1.20.1-build.147.jar.zip) (0.6.1 had networking issues on Forge and this patch shows incorrect fuel requirements in some Blaze Mixing recipes on servers). It's made for Create 0.5.1.f, but it should also work for patch h.
Let me know if that version works.

**Comment by Astrolava** [comment]
Okay, thank you for the update.  I will attempt to use 0.6.1 for the time being.

**Comment by dudek26** [comment]
Hi, I think I've solved the issue, could you check if there are any problems with this version?
[create_blazing_hot-0.6.3+forge-mc1.20.1-build.171.zip](https://github.com/user-attachments/files/17269760/create_blazing_hot-0.6.3%2Bforge-mc1.20.1-build.171.zip)

**Comment by Astrolava** [comment]
hey there, I've just tested it, and I was able to load up my world.  I've only since played with the nether lava in the overworld so far.
I'll let you know if there are any further issues.
Once again, thank you.

**Comment by dudek26** [comment]
[fixed in v0.6.3](https://modrinth.com/mod/create-blazing-hot/version/0.6.3+forge-mc1.20.1)
