### ISSUE TITLE
[Question] How to properly register new metals

### ISSUE THREAD

**Issue by kienerxyzzy** [dudek26/Create-Blazing-Hot#8]
I'm playing a modpack with loads of metals (alumium, nickel, tin, osmium,...) and I would like an easy way to register them.

**Comment by dudek26** [comment]
hi, molten metals are hard-coded and they can't be registered by modpack developers

**Comment by kienerxyzzy** [comment]
:(
maybe a new feature suggestion?

**Comment by dudek26** [comment]
I'm planning on supporting metals from other mods in the future
